### ISSUE TITLE
Protect apigee api via JWT claim role

### ISSUE THREAD

**Issue by spiazzi** [DinoChiesa/ApigeeEdge-JWT-Demonstration#4]
Is there a way to protect api on a role based approach?
The scenario is that and external IDP generate a jwt token with an additional claims that give the user role.
Base on that claim I want to protect apigee api, that is allow or not to access to that api based on this role.

Is there a standard way to map this claim to a user role and the use this:
https://apidocs.apigee.com/docs/user-roles/1/overview
?

I saw other idea to maintanin a KVM or a callout for an auth services:
https://community.apigee.com/questions/50170/scope-user-role-mapping.html

But I think it is better to use standard user roles form apigee with a mapping.

**Comment by DinoChiesa** [comment]
Yes, you can protect an API based on role, or... said more generally, based on an arbitrary claim contained in the JWT.

There are two ways to do it. 

Option 1:
First, you can do it with a RaiseFault step decorated with a <Condition> element following the VerifyJWT step.  The Condition will test the value of a context variable, representing the scope. If the required scope is not present, the RaiseFault will raise a fault. 

```
  <Step>
     <Name>VerifyJWT-1</Name>
  </Step>
  <Step>
      <Condition>jwt.VerifyJWT-1.decoded.claim.scope != "read"</Condition>
      <Name>RF-Unauthorized-Scope</Name>
  </Step>
```

details:

When you use the VerifyJWT policy within an Apigee API Proxy, and the verification is _unsuccessful_, then the VerifyJWT policy raises a fault, and processing continues in the FaultRules. This might happen because: 

- the key you specify cannot verify the signature on the JWT
- the JWT uses the wrong algorithm (does not match what is configured in the VerifyJWT policy)
- The JWT is expired.
- Other standard claims that you check via VerifyJWT (incl iss, sub, aud, and so on) do not match
- other custom claims that you check via the policy configuration does not match. 

If the VerifyJWT succeeds, it sets into message context a set of variables containing values for all the claims in the verified JWT.  You can then examine and test these variables in subsequent steps. 

Option 2: 
You can verify the required claim directly in the VerifyJWT policy. Example: 

```
  <VerifyJWT name='VJWT-1'>
    <Algorithm>RS256</Algorithm>
    <PublicKey>
      <Value ref='my_public_key'/>
    </PublicKey>
    <AdditionalClaims>
      <Claim name='scope'>read</Claim>
    </AdditionalClaims>
  </VerifyJWT>
```

This policy will throw if the presented JWT is expired, can't be verified with the given key, has the wrong alg, OR has a scope claim that is not "read".

**Comment by spiazzi** [comment]
This is interesting, but in a situation where there are different groups and should be that could be asked to have fine tuned authorizations, that is only few method of the api proxy available for certains groups, is there the possibility to use the default apigee roles permission and map the claims and identity to the apiegee group and inherits the permission to the api ?

Otherwise I guess I have to use a KVM or an external az services?

**Comment by DinoChiesa** [comment]
>  is there the possibility to use the default apigee roles permission and map the claims and identity to the apiegee group and inherits the permission to the api ?

The roles stored by Apigee apply to Operators and Administrators of Apigee. 
What we are talking about here is API proxies. The "user" on the sending end, is not an Apigee operator or administrator.  That user need not be known by Apigee. 

So, yes, I think you need to have an external store that describes how to authorize particular calls. 
I have [a separate repo](https://github.com/DinoChiesa/Apigee-External-Authorization-1) (with a screencast!) that provides an example for that idea.   It does not rely on JWT, but ... one could imagine combining a claim in the JWT with the externalized Authorization database to arrive at an authorization decision.
